rr-wfm/MSBuild.Sdk.SqlProj

.gitignore, LICENSE, src/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj.csproj, src/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj.nuspec
Hi @jmezach , this looks like something we'd really like to use for some of our internal projects at Denver Health.  Any chance I can get you to add a license?  I suggested MIT simply because it is well known and permissive which I think may be consistent with what [you wrote](https://jmezach.github.io/post/introducing-msbuild-sdk-sqlproj/).
Please feel free to squash on completion since I didn't realize that the GitHub License file would automatically include my name.
=> Add a license

src/BuildDacpac/PackageBuilderOptions.cs, src/BuildDacpac/Program.cs
part of #6 (implements https://github.com/dotnet/command-line-api/issues/458 )
@jmezach I leave the MsBuild changes to you, I have no idea where to start (or end, for that matter)
Tested by running "dotnet build" against the test projects.
=> Add command line support for adding SqlCmdVariables

src/BuildDacpac/BuildDacpac.csproj, src/BuildDacpac/Program.cs, src/MSBuild.Sdk.SqlProj/Sdk/Sdk.props, src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets, test/TestProjectWithSqlCmdVariables/TestProjectWithSqlCmdVariables.csproj
This is the last stretch towards implementing #6. It adds the necessary wiring in the MSBuild stuff to pass the SqlCmd variables defined in the project file to the command line tool, which can then add the requested variables to the `.dacpac`.
=> Implement support for SqlCmd variables

.github/workflows/main.yml, README.md, src/MSBuild.Sdk.SqlProj.Templates/MSBuild.Sdk.SqlProj.Templates.csproj, src/MSBuild.Sdk.SqlProj.Templates/templates/inlinefunc/.template.config/template.json, src/MSBuild.Sdk.SqlProj.Templates/templates/inlinefunc/Function1.sql, src/MSBuild.Sdk.SqlProj.Templates/templates/scalarfunc/.template.config/template.json, src/MSBuild.Sdk.SqlProj.Templates/templates/scalarfunc/Function1.sql, src/MSBuild.Sdk.SqlProj.Templates/templates/sproc/.template.config/template.json, src/MSBuild.Sdk.SqlProj.Templates/templates/sproc/Procedure1.sql, src/MSBuild.Sdk.SqlProj.Templates/templates/sqlproj/.template.config/template.json, src/MSBuild.Sdk.SqlProj.Templates/templates/sqlproj/sqlproj.csproj, src/MSBuild.Sdk.SqlProj.Templates/templates/sqlproj/sqlproj.nuspec, src/MSBuild.Sdk.SqlProj.Templates/templates/table/.template.config/template.json, src/MSBuild.Sdk.SqlProj.Templates/templates/table/Table1.sql, src/MSBuild.Sdk.SqlProj.Templates/templates/tablefunc/.template.config/template.json, src/MSBuild.Sdk.SqlProj.Templates/templates/tablefunc/Function1.sql, src/MSBuild.Sdk.SqlProj.Templates/templates/view/.template.config/template.json, src/MSBuild.Sdk.SqlProj.Templates/templates/view/View1.sql
This adds a new NuGet package containing a set of templates that can be installed using `dotnet new`. It can then be used to create new projects that use MSBuild.Sdk.SqlProj. I've also included a set of item templates that can be used to quickly create new database objects. I've concentrated on the mostly used objects like tables, views and stored procedures for now, but other objects can be added fairly easily if needed.
The project template is created in such a way that it should align with the appropriate release of the SDK package. So if you have the MSBuild.Sdk.SqlProj.Templates 1.4.0 package installed and you create a new project using `dotnet new sqlproj` you get a `.csproj` with `Sdk="MSBuild.Sdk.SqlProj/1.4.0".
I've already tried this with the preview feature in VS 2019 16.8 …
=> Add a template pack

src/DacpacTool/BuildOptions.cs, src/DacpacTool/PackageBuilder.cs, src/DacpacTool/Program.cs, src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets, test/DacpacTool.Tests/PackageBuilderTests.cs, test/TestProjectWithPrePost/RefactorLog/TestProjectWithPrePost.refactorlog, test/TestProjectWithPrePost/TestProjectWithPrePost.csproj
added support for .refactorlog files handled by the original `.sqlproj`
#45
=> add support for refactor log script files

.github/workflows/main.yml, src/DacpacTool/DacpacTool.csproj, src/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj.csproj
This adds support for .NET 5 previews so that folks having the preview installed can still build their projects without needing to put a `global.json` somewhere. Essentially this means that we're now building the `DacpacTool` for .NET 5 as well and include that into the `MSBuild.Sdk.SqlProj` package. At build time we pick the appropriate version depending on the .NET runtime included with the SDK.
I've also extended the CI pipeline to start building with .NET 5.0 as well. So far this seems to work just fine. We'll need to keep this up-to-date until the stable release hits in november.
Fixes #52
=> Add .NET 5.0 support

src/DacpacTool/BuildOptions.cs, src/DacpacTool/DacpacTool.csproj, src/DacpacTool/Extensions.cs, src/DacpacTool/PackageBuilder.cs, src/DacpacTool/Program.cs, src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets, test/DacpacTool.Tests/PackageBuilderTests.cs, test/DacpacTool.Tests/TestModelBuilder.cs, test/TestProjectWithExternalPackageReference/TestProjectWithExternalPackageReferencs.csproj, test/TestProjectWithExternalPackageReference/csp_Test.sql
So far we've only had support for package references that represent objects within the same database so that you can define SQL objects in a separate project, package that up into a NuGet package and then re-use those objects in your own project. The old SSDT projects also support adding a reference to another `.dacpac` where that reference represents an entirely different database. This PR adds that support to `MSBuild.Sdk.SqlProj` as well which is controlled by setting the `DatabaseVariableLiteralValue` item metadata on the `PackageReference`, similar to how this works in SSDT projects.
Fixes #51
=> Support for package references representing external databases

src/DacpacTool/BuildOptions.cs, src/DacpacTool/Program.cs, src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets
I've left the existing code for `--input`, just in case anyone is trying to call the DacpacTool CLI directly, but added `--inputfile` and changed `Sdk.targets` to use that instead. The new intermediate file is added to the `obj/` directory.
=> Use an intermediate file containing each object definition

README.md, src/MSBuild.Sdk.SqlProj.Templates/templates/inlinefunc/.template.config/template.json, src/MSBuild.Sdk.SqlProj.Templates/templates/inlinefunc/Function1.sql, src/MSBuild.Sdk.SqlProj.Templates/templates/scalarfunc/.template.config/template.json, src/MSBuild.Sdk.SqlProj.Templates/templates/scalarfunc/Function1.sql, src/MSBuild.Sdk.SqlProj.Templates/templates/sproc/.template.config/template.json, src/MSBuild.Sdk.SqlProj.Templates/templates/sproc/Procedure1.sql, src/MSBuild.Sdk.SqlProj.Templates/templates/table/.template.config/template.json, src/MSBuild.Sdk.SqlProj.Templates/templates/table/Table1.sql, src/MSBuild.Sdk.SqlProj.Templates/templates/tablefunc/.template.config/template.json, src/MSBuild.Sdk.SqlProj.Templates/templates/tablefunc/Function1.sql, src/MSBuild.Sdk.SqlProj.Templates/templates/uddt/.template.config/template.json, src/MSBuild.Sdk.SqlProj.Templates/templates/uddt/UserDefinedDataType1.sql, src/MSBuild.Sdk.SqlProj.Templates/templates/udtt/.template.config/template.json, src/MSBuild.Sdk.SqlProj.Templates/templates/udtt/UserDefinedTableType1.sql, src/MSBuild.Sdk.SqlProj.Templates/templates/view/.template.config/template.json, src/MSBuild.Sdk.SqlProj.Templates/templates/view/View1.sql
This adds two new item templates to the template pack introduced in 1.4.0, namely user-defined data types and user-defined table types. We are using the latter quite a lot. I've also added a schemaName parameter to all of the item templates so that you can run `dotnet new sproc -n MyStoredProcedure -s MySchema` and immediately have a stored procedure with the correct name and schema created for you.
=> Add additional item templates and schema name support

README.md
Per discussion on #67, this adds documentation to help users create a NuGet package from an existing .dacpac file. No code changes, documentation only.
=> Document the process for packaging a standalone .dacpac file

README.md, src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets, test/TestProjectWithProjectReference/TestProjectWithProjectReference.csproj
In addition to package references you might also want to reference another project (possibly within the same solution). This adds support for that. Luckily most of the heavy lifting is already done for us, so all we really needed to do is to make sure we support getting a target path of the `.dacpac` without building the project and then resolving that target path into a reference parameter for the `DacpacTool`.
Fixes #40
=> Add support for project references

src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets
We discovered an issue with the Fast Up-to-date check feature of Visual Studio. It seemed to be looking for debug symbols, but they are never produced by an MSBuild.Sdk.SqlProj project. So we made that explicit now, which seems to fix the issue with fast-up-to-date check.
Fixes: #74
=> Fix up-to-date-check issue

src/DacpacTool/PackageDeployer.cs, test/TestProject/TestProject.csproj, test/TestProjectWithErrors/TestProjectWithErrors.csproj, test/TestProjectWithExternalPackageReference/TestProjectWithExternalPackageReferencs.csproj, test/TestProjectWithPackageReference/TestProjectWithPackageReference.csproj, test/TestProjectWithPrePost/TestProjectWithPrePost.csproj, test/TestProjectWithWarnings/TestProjectWithWarnings.csproj
As mentioned in #70 the output for the publish pipeline isn't ideal which leads to users having to figure out by themselves what's going wrong. This PR changes the way we handle exceptions by looking for an InnerException and writing the message from that, rather than the `DacServicesException` which tells us nothing more than that the deployment failed.
I've also hooked up the `Message` event so that we get some more output from the deployment. Essentially you now get the same output as you would get when running `SqlPackage.exe` which can be useful to diagnose problems.
Fixes: #70
=> Improved error handling for publish pipeline

.github/workflows/main.yml, README.md, src/MSBuild.Sdk.SqlProj/Sdk/Sdk.props, src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets, test/TestProject/TestProject.csproj
We should allow users to allow to specify a different name for the `.dacpac` file if they choose to do so. This could already be achieved by specifying `<AssemblyName>` in the `.csproj` but when specifying an alternative name it would break `dotnet publish` since it would still look for the `.dacpac` using the projects name. This has now been fixed.
While working on this I also discovered the `<TargetName>` property which can also be set to control the name of the output file, which probably makes a little bit more sense than setting '`<AssemblyName>'. I'll make sure to add that to the docs before completing this PR.
It is probably also worth noting that we currently expect the `.dacpac` to have the same name as the NuGet package when used as a '<PackageReference>`. I'll make sure that I …
=> Allow specifying an alternative file name for the .dacpac

.github/workflows/main.yml, Directory.Build.props, src/DacpacTool/DeployOptions.cs, src/DacpacTool/PackageDeployer.cs, src/DacpacTool/Program.cs, src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets, test/DacpacTool.Tests/PackageDeployerTests.cs
This PR creates a new `UseTargetServerAndPort` method, called only if the user passes in a port. If a port isn't specified, rather than using a default port of 1433, we just fall back to the existing method of not including the port in the connection string at all.
=> Allow users to specify an explicit port for publishing (#97)

README.md, src/DacpacTool/DacpacTool.csproj, src/DacpacTool/DeployOptions.cs, src/DacpacTool/Extensions.cs, src/DacpacTool/PackageBuilder.cs, src/DacpacTool/PackageDeployer.cs, src/DacpacTool/Program.cs, src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets, test/DacpacTool.Tests/DacpacHeaderParser/DacpacXml.cs, test/DacpacTool.Tests/DacpacTool.Tests.csproj, test/DacpacTool.Tests/ExtensionsTest.cs, test/DacpacTool.Tests/PackageBuilderTests.cs, test/DacpacTool.Tests/PackageDeployerTests.cs, test/TestProjectWithPrePost/Post-Deployment/Script.PostDeployment.sql, test/TestProjectWithPrePost/TestProjectWithPrePost.csproj, test/TestProjectWithPrePostDependency/TestProjectWithPrePostDependency.csproj
When referencing other database packages, either by using a `ProjectReference` or a `PackageReference`, the pre- and/or post-deployment scripts of those dependencies are not run during deployment. While this is understandable in a deployment pipeline when using `SqlPackage.exe` it can be desirable when developers need to update their local development databases. For example, when the post-deployment script inserts some well-known data into certain tables, a developer might expect to have that data in his local development database. In this PR I've added opt-in support to allow for this.
Fixes #110
=> Allow running pre/post deployment scripts for referenced packages

README.md, src/DacpacTool/DacpacTool.csproj, src/DacpacTool/PackageDeployer.cs, test/DacpacTool.Tests/PackageDeployerTests.cs, test/TestProject/TestProject.csproj
Due to how semi-colons are parsed by shells the previous implementation using a semi-colon separated list of values doesn't actually work. I've now changed this to be comma separated instead. As discussed in #104 this is technically a breaking change, but since the old implementation didn't work either I don't think we have to sweat it.
I've also added the clarification discussed in #103 about `dotnet publish` support being targetted at developers updating their local databases and we suggest using SqlPackage.exe for more advanced scenario's .
Fixes #104 
Fixes #103
=> Use comma separation for complex deploy options

src/MSBuild.Sdk.SqlProj/Sdk/Sdk.props, test/DacpacTool.Tests/ScriptParserTests.cs
Nothing major here -- just a few quick things that came up in the discussion of #114:
1. Edited Sdk.props to use forward-slashes instead of backslashes
2. Edited Sdk.props to exclude content from `bin/` and `obj`
3. Added an additional test to `ScriptParserTests.cs` to double-check the issue reported in #114, and decided that since I had already added it, I may as well keep it in there
=> Exclude scripts from bin/ and obj/ directories, add additional test case per discussion on #114

src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets
As discussed in #123 it appears that the `.dacpac` from a `ProjectReference` is passed to the `ResolveAssemblyReferences` target which sometimes fails, apparently due to the size of the `.dacpac`. Since that target treats the file as a .NET assembly it doesn't really make sense to process it through that target at all. So now we're explicitly removing any referenced `.dacpac` from the `_ResolvedProjectReferencePaths` item so it isn't processed by the `ResolveAssemblyReferences` target. Note that the reference is still being used to compile the `.dacpac` so that project references still work as before.
Fixes #123
=> Explicitly remove .dacpacs from assemblyreferences

README.md, src/DacpacTool/BuildOptions.cs, src/DacpacTool/ModelValidationError.cs, src/DacpacTool/PackageBuilder.cs, src/DacpacTool/Program.cs, src/MSBuild.Sdk.SqlProj/Sdk/Sdk.props, src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets, test/DacpacTool.Tests/PackageBuilderTests.cs, test/TestProjectWithWarningsSuppress/Procedures/csp_Test.sql, test/TestProjectWithWarningsSuppress/TestProjectWithWarningsSuppress.csproj
In standard Microsoft Database project there is an options controlling how to treat T-SQL Warnings.
The global project option TreatTSqlWarningsAsErrors tells to break compiling on any waring  is occured. Individual warnings can be suppressed by SuppressTSqlWarnings option. It is a list of warning codes.
So I try to add support for both options at project level. Suppressing warnings for individual files may be done later.
To use it simply add 
```
<TreatTSqlWarningsAsErrors>True</TreatTSqlWarningsAsErrors>
<SuppressTSqlWarnings>71558</SuppressTSqlWarnings>
```
to Project PropertyGroup.
Added test Project TestProjectWithWarningsSuppress
Added tests to DacpacTool.Tests
=> Adding support for TreatTSqlWarningsAsErrors and SuppressTSqlWarnings

src/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj.nuspec
Implemented as per https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/
@jmezach Can you please [verify](https://docs.microsoft.com/en-us/nuget/nuget-org/publish-a-package#web-portal-use-the-upload-package-tab-on-nugetorg) that the readme shows up?
=> Include README.md in the nuget package

README.md, src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets, test/TestIncludeFromVanillaProj/Class1.cs, test/TestIncludeFromVanillaProj/TestIncludeFromVanillaProj.csproj, test/TestIncludeFromVanillaProjWithExternalPackageReference/Class1.cs, test/TestIncludeFromVanillaProjWithExternalPackageReference/TestIncludeFromVanillaProjWithExternalPackageReference.csproj, test/TestProjectWithExternalPackageReference/TestProjectWithExternalPackageReference.csproj
This solves #117 
Take care to add `<ReferenceOutputAssembly>False</ReferenceOutputAssembly>` to the project reference. Without it, the compilation of the vanilla class library will fail; a `.dacpac` file is not a valid assembly ;-)
The target `GetCopyToOutputDirectoryItems` returns an `AllItemsFullPathWithTargetPath` item collection. The new target `CopyDacpacs` runs before `GetCopyToOutputDirectoryItems` and preloads `AllItemsFullPathWithTargetPath` with the project's dacpac file and all referenced dacpac files.
Two test projects prove that the referenced dacpac files get copied to the bin folder of the vanilla class library project:
- TestIncludeFromVanillaProj
This uses a `ProjectReference` to a dacpac project with a nested `ProjectReference`.
- …
=> Allow project reference from vanilla classlib

README.md, src/DacpacTool/BuildOptions.cs, src/DacpacTool/PackageBuilder.cs, src/DacpacTool/Program.cs, src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets, test/DacpacTool.Tests/PackageBuilderTests.cs, test/DacpacTool.Tests/ScriptParserTests.cs, test/TestProjectWithGenerateScriptAndTargetDatabaseName/Tables/MyTable.sql, test/TestProjectWithGenerateScriptAndTargetDatabaseName/TestProjectWithGenerateScriptAndTargetDatabaseName.csproj
Apply `TargetDatabaseName`, which is normally used for publishing the dacpac, to the generated create script as well. See issue #186
=> Apply TargetDatabaseName in GenerateCreateScript

README.md, src/DacpacTool/BuildOptions.cs, src/DacpacTool/PackageBuilder.cs, src/DacpacTool/Program.cs, src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets, test/DacpacTool.Tests/PackageBuilderTests.cs
Add an `IncludeCompositeObjects` option that allows to include objects from the referenced database packages when generating the script file
=> Include composite objects from external references when generating script file

README.md, src/DacpacTool/BuildOptions.cs, src/DacpacTool/DatabaseProperty.cs, src/DacpacTool/PackageBuilder.cs, src/DacpacTool/PackageDeployer.cs, src/DacpacTool/Program.cs, src/DacpacTool/PropertyParser.cs, src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets, test/DacpacTool.Tests/PackageBuilderTests.cs, test/DacpacTool.Tests/PackageDeployerTests.cs, test/DacpacTool.Tests/PropertyParserTest.cs, test/TestProjectWithGenerateScriptAndTargetDatabaseName/TestProjectWithGenerateScriptAndTargetDatabaseName.csproj
This PR allows setting all the possible properties in the `GenerateCreateScript` functionality. The properties defined in the `csproj` (the `KnownDeployProperties` ones) are now automatically set when generating the create script
Solves issue #230
=> Pass down KnownDeployProperties to the GenerateCreateScript functionality

README.md, src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets, test/TestProjectWithMasterReference/Procedures/csp_MyProcedureThatUsesMaster.sql, test/TestProjectWithMasterReference/TestProjectWithMasterReference.csproj, test/TestProjectWithPackageReference/TestProjectWithPackageReference.csproj
Microsoft has released NuGet packages containing the `.dacpac` of the `master` and `msdb` databases. They decided to ship a single `Microsoft.SqlServer.Dacpacs` package containing both of them however, which `MSBuild.Sdk.SqlProj` currently has no way of supporting as we're assuming that the name of the `.dacpac` is the same as package.
To remedy this I've added support for overriding the name of the `.dacpac` within the package on a per-package reference basis. I believe this is a generally useful feature, but works especially well with these newly released packages.
Fixes #396
=> Allow overriding the dacpac filename

src/DacpacTool/Program.cs
=> Attempt to fix issue with extra command line arguments

README.md, src/DacpacTool/PackageAnalyzer.cs, src/DacpacTool/SqlRuleProblemExtensions.cs, test/DacpacTool.Tests/PackageAnalyzerTests.cs, test/TestProjectWithAnalyzers/TestProjectWithAnalyzers.csproj
=> Add ability to treat rule violations as errors

src/DacpacTool/DacpacTool.csproj, src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets
fixes #531
Also updates the rules to avoid false positives due to temporal tables:  https://github.com/ErikEJ/SqlServer.Rules/commit/a2b6197258c10d00e52905ec822ef44657fde699
=> Add quotes around rules list and fix temporal table rules issues

README.md, src/DacpacTool/SqlRuleProblemExtensions.cs, test/DacpacTool.Tests/PackageAnalyzerTests.cs
=> Enable error wildcards

.github/workflows/main.yml, global.json, src/DacpacTool/Extensions.cs, src/DacpacTool/PackageBuilder.cs, src/DacpacTool/Program.cs, test/DacpacTool.Tests/PackageBuilderTests.cs, test/TestProjectWithExceptions/Tables/MyTable.sql, test/TestProjectWithExceptions/Tables/MyTable2.sql, test/TestProjectWithExceptions/TestProjectWithExceptions.csproj
=> Report DacModelExceptions better, and continue processing all files

README.md, test/TestProjectWithMasterReference/TestProjectWithMasterReference.csproj
=> Verify that GenerateCreateScript works

.github/workflows/main.yml, README.md, src/DacpacTool/BaseOptions.cs, src/DacpacTool/DacpacTool.csproj, src/DacpacTool/DatabaseProperty.cs, src/DacpacTool/DeployOptions.cs, src/DacpacTool/IncludeVariableResolver.cs, src/DacpacTool/ModelValidationError.cs, src/DacpacTool/PackageAnalyzer.cs, src/DacpacTool/PackageBuilder.cs, src/DacpacTool/PackageDeployer.cs, src/DacpacTool/PropertyParser.cs, src/DacpacTool/ScriptInspector.cs, src/DacpacTool/ScriptParser.cs, src/DacpacTool/SqlRuleProblemExtensions.cs, src/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj.csproj, test/DacpacTool.Tests/DacpacTool.Tests.csproj
Also: removed .NET 7 support and updated readme to 2.8.1
```xml
<AnalysisMode>all</AnalysisMode>
<EnableNETAnalyzers>true</EnableNETAnalyzers>
<AnalysisLevel>latest</AnalysisLevel>
<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
```
=> Code cleanup from temporary enabling .NET analyzers

src/DacpacTool/DacpacTool.csproj, src/DacpacTool/IVersionProvider.cs, src/DacpacTool/Program.cs, src/DacpacTool/VersionChecker.cs, src/DacpacTool/VersionProvider.cs, test/DacpacTool.Tests/PackageAnalyzerTests.cs, test/DacpacTool.Tests/TestVersionProvider.cs, test/DacpacTool.Tests/VersionCheckerTests.cs
=> Add a version check and warn if not using latest

README.md
=> Add refactor log docs

README.md, src/DacpacTool/PackageAnalyzer.cs, test/DacpacTool.Tests/DacpacTool.Tests.csproj, test/DacpacTool.Tests/PackageAnalyzerTests.cs
=> Fix broken warning (it never appears if any .NET analyzers are present)

README.md, src/DacpacTool/Extensions.cs, test/DacpacTool.Tests/DacpacTool.Tests.csproj, test/DacpacTool.Tests/PackageBuilderTests.cs
https://learn.microsoft.com/sql/tools/sql-database-projects/concepts/sqlcmd-variables
fixes #448
=> SqlCmdVariable DefaultValue should not be written to .dacpac as per docs

README.md
A couple of the code blocks have improper termination of their fenced-off markdown, and (in one case) were preventing the _Pre- and post deployment scripts_ subheading from rendering.  Clean up the code blocks so they (and markup that follows them) are rendered properly.
=> Correct fenced-in code blocks

MSBuild.Sdk.SqlProj.sln, README.md, src/DacpacTool/PackageAnalyzer.cs, src/MSBuild.Sdk.SqlProj.Templates/templates/sqlproj/sqlproj.csproj
This was discovered during a debugging session with the AdventureWorks schema.
Changed the implementation to always report any errors.
Updated SqlServer.Rules: This analyzer was previously split into two .dll files, and this was not handled well in multiple scenarios
Updated TSqlSmellsSCA: Fixed NRE triggered by Computed columns in AdventureWorks schema
fixes #707
=> Even if AnalysisSucceded, there could be errors from analysis. 

README.md
add SQL CLR section
fixes #109
=> Update readme for 3.1.0 & add SQLCLR section

src/DacpacTool/PackageAnalyzer.cs, src/DacpacTool/VersionChecker.cs, test/DacpacTool.Tests/PackageAnalyzerTests.cs
=> Add info about how to ignore warning message

.github/workflows/main.yml
This enables the use of Trusted Publishing for publishing our NuGet packages to NuGet.org enhancing security.
Fixes #787
=> Use Trusted Publishing
