README.md

Found some typo's in the code examples in the README file.

Fixed some typo's in the README file

---

src/BuildDacpac/PackageBuilder.cs
test/TestProjectWithPrePost/Post-Deployment/Script.PostDeployment.sql

Fix stream writing bug (different encoding with BOM)

---

.github/workflows/main.yml
src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets
test/TestProjectWithSDKRef/TestProjectWithSDKRef.csproj

For packages that meet certain criteria (such as having a tools folder), MSBuild will automatically include a property that resolves their location. This is more accurate because it handles floating versions$

Use the MSBuild Pkg<package-id> property for package location (#36)

---

CONTRIBUTING.md
src/DacpacTool/BuildOptions.cs
src/DacpacTool/DeployOptions.cs
src/DacpacTool/Extensions.cs
src/DacpacTool/ModelValidationError.cs
src/DacpacTool/PackageBuilder.cs
src/DacpacTool/Program.cs
src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets
test/DacpacTool.Tests/ExtensionsTest.cs
test/DacpacTool.Tests/TestModelBuilder.cs

Not able to get any file or line info, though

Improve display of validation errors

---

src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets

As far as I can tell, this seems to be all we need to fix #48. [Here's the relevant documentation](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-build-incrementally?view=vs-2019)

Add CoreCompile inputs so they'll be checked for incremental changes

---

README.md

Explanation of `AssemblyName`
Resolves #65

Explanation of `AssemblyName`

---

README.md

I'm not sure if this line should be edited or removed.
The problem was introduced by me in #66

AssemblyName is now TargetName

---

README.md

Added sections `Editing the Project file` and `Item templates`.
Resolves #87

`Editing the Project file` and `Item templates`

---

README.md

Explains how to go from the SQL Server SKU name to the SqlServerVersion enum.
Resolves #86
I broke #88 by deleting my fork!

README: SQL Server SKU name to SqlServerVersion enum

---

README.md

As requested in [this comment](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/pull/100#issuecomment-733190886). Sorry this took so long, I missed the comment while I was offline for the holidays.

Document the TargetPort property (#97)

---

src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets

Improve error message.

---

src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets
test/TestProjectWithWarningsAsErrorsAndTSqlFalse/Procedures/csp_Test.sql
test/TestProjectWithWarningsAsErrorsAndTSqlFalse/TestProjectWithWarningsAsErrorsAndTSqlFalse.csproj

Ignore `TreatWarningsAsErrors` if `TreatTSqlWarningsAsErrors` has been set. See #185

Let TreatTSqlWarningsAsErrors win

---

.github/workflows/main.yml
src/DacpacTool/DacpacTool.csproj
src/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj.csproj
src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets
test/DacpacTool.Tests/DacpacTool.Tests.csproj
test/TestProject/global.json
version.json

Solves #192 and adds support for net6.0

Remove support for netcoreapp2.1 and add support for net6.0

---

MSBuild.Sdk.SqlProj.sln
README.md
src/DacpacTool/Extensions.cs
src/DacpacTool/PackageBuilder.cs
src/DacpacTool/Program.cs
src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets
test/DacpacTool.Tests/PackageBuilderTests.cs
test/DacpacTool.Tests/TestModelBuilder.cs
test/TestProjectWithSuppressMissingDependencies/Procedures/csp_Test.sql
test/TestProjectWithSuppressMissingDependencies/TestProjectWithSuppressMissingDependencies.csproj

- Works for both project and package references

Add SuppressMissingDependenciesErrors option support

---

.github/workflows/main.yml
src/DacpacTool/DacpacTool.csproj
src/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj.csproj
test/DacpacTool.Tests/DacpacTool.Tests.csproj

@jmezach @jeffrosenberg  I do not understand versioning - where do I set it? Or it it set by magic 🧙 ? 
fixes #353

Support .NET 7.0 RTM

---

.github/workflows/main.yml
src/DacpacTool/DacpacTool.csproj
src/DacpacTool/DeployOptions.cs
src/DacpacTool/PackageDeployer.cs
src/DacpacTool/Program.cs
test/DacpacTool.Tests/PackageDeployerTests.cs

Use microsoft.sqlpackage on container

Use DacFx for SQL Server 2022

---

.github/workflows/main.yml

attempt to use the Ubuntu 22 agents

---

.github/workflows/main.yml

as per https://techcommunity.microsoft.com/t5/azure-sql-blog/connection-security-improvements-in-sqlpackage-161/ba-p/3672758

fix sqlpackage 161 pipeline break

---

src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets

Add Capability to enable check via Visual Studio SDK

---

.github/workflows/main.yml
CONTRIBUTING.md
src/DacpacTool/DacpacTool.csproj
src/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj.csproj
test/DacpacTool.Tests/DacpacTool.Tests.csproj

Remove support for .NET Core 3.1

---

README.md

Partially addresses pain of #222 and #239.

Call out NS2.0 dependency in README

---

src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets
test/TestProjectWithSqlCmdVariables/TestProjectWithSqlCmdVariables.csproj

Fixes #458
Signed-off-by: Jonathan Mezach <jonathan.mezach@rr-wfm.com>

Fix escaping issue with SQLCMD params

---

README.md
test/TestProjectWithMasterReference/TestProjectWithMasterReference.csproj

Update readme to latest release version

Update docs re system .dacpacs

---

src/DacpacTool/DacpacTool.csproj

https://learn.microsoft.com/en-us/sql/tools/sqlpackage/release-notes-sqlpackage?view=sql-server-ver16#1622111-sqlpackage

Update to latest DacFX

---

src/MSBuild.Sdk.SqlProj.Templates/templates/sqlproj/.template.config/template.json
src/MSBuild.Sdk.SqlProj.Templates/templates/sqlproj/sqlproj.csproj

update template for Sql160
fixes #537

always enable sql code analysis

---

src/DacpacTool/DacpacTool.csproj

see https://github.com/ErikEJ/SqlServer.Rules/commit/c6f7a3e91b0c274c3ef99e21cb7e947942d0f441

Update rules with some NRE fixes

---

src/DacpacTool/DacpacTool.csproj

Fix false positive

---

README.md

Improve Dacpacs docs

---

README.md

Remove reference to packageType in .nuspec

---

.editorconfig
src/DacpacTool/BuildOptions.cs
src/DacpacTool/DacpacTool.csproj
src/DacpacTool/DatabaseProperty.cs
src/DacpacTool/DeployOptions.cs
src/DacpacTool/Extensions.cs
src/DacpacTool/PackageAnalyzer.cs
src/DacpacTool/PackageBuilder.cs
src/DacpacTool/PackageDeployer.cs
src/DacpacTool/Program.cs
src/DacpacTool/PropertyParser.cs
src/DacpacTool/ScriptInspector.cs

Enable .NET Analyzers in DacpacTool

---

README.md
src/MSBuild.Sdk.SqlProj.Templates/templates/sqlproj/sqlproj.csproj

Readme overhaul for 3.0

---

README.md
src/DacpacTool/DacpacTool.csproj
src/MSBuild.Sdk.SqlProj.Templates/templates/sqlproj/sqlproj.csproj
test/TestProjectWithAnalyzers/TestProjectWithAnalyzers.csproj

Update template and readme

---

src/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj.csproj

Update SDK package dependencies

---

README.md
src/MSBuild.Sdk.SqlProj.Templates/templates/sqlproj/sqlproj.csproj

Use latest rules packages, which have links to rule documentation 

---

src/DacpacTool/DacpacTool.csproj
src/DacpacTool/VersionChecker.cs
test/DacpacTool.Tests/DacpacTool.Tests.csproj
test/TestProject/global.json

show dacfx version during build

---

src/DacpacTool/Extensions.cs
src/DacpacTool/PackageBuilder.cs
test/DacpacTool.Tests/PackageBuilderTests.cs
test/DacpacTool.Tests/TestConsole.cs

Fix logging of DacModelExceptions

---

.github/workflows/main.yml
README.md
src/DacpacTool/DacpacTool.csproj
src/MSBuild.Sdk.SqlProj.Templates/templates/sqlproj/.template.config/template.json
src/MSBuild.Sdk.SqlProj.Templates/templates/sqlproj/sqlproj.csproj

Minor pipeline and readme housekeeping
fixes #742

Use latest DacFX and analyzers

---

.github/workflows/main.yml
src/MSBuild.Sdk.SqlProj.Templates/templates/sqlproj/sqlproj.csproj
src/MSBuild.Sdk.SqlProj/Sdk/Sdk.props
test/TestProject/TestProject.csproj
test/TestProjectWithAnalyzers/TestProjectWithAnalyzers.csproj
test/TestProjectWithSDKRef/TestProjectWithSDKRef.csproj

enable net8.0 target framework

---

src/DacpacTool/VersionChecker.cs

Avoid daily perf hit from version check

---

test/DacpacTool.Tests/DacpacTool.Tests.csproj
test/DacpacTool.Tests/PackageBuilderTests.cs

fix test assertion

---

src/MSBuild.Sdk.SqlProj.Templates/templates/sqlproj/.template.config/template.json

Improve project template

---

README.md
src/DacpacTool/DacpacTool.csproj

Prepare for release 3.2

---

README.md
src/MSBuild.Sdk.SqlProj.Templates/templates/sqlproj/sqlproj.csproj

release notes here: https://github.com/ErikEJ/SqlServer.Rules/releases/tag/v3.0.0

Use analyzers version 3
